name = "LAMBS Danger"
prefix = "lambs"
author = "LAMBS Dev Team"
mainprefix = "z"

[version]
major = 2
minor = 6
patch = 1
build = 0
git_hash = 0

[files]
include = [
    "mod.cpp",
    "*.paa",
    "LICENSE",
    "readme.txt",
    "readme.md"
]

[asc]
enabled = true

[hemtt.signing]
authority = "LambsDanger"

[hemtt.release]
folder = "lambs_danger"
