name: Arma

on:
  push:
    branches:
    - master
  pull_request:
    
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate SQF
      run: python3 tools/sqf_validator.py
    - name: Validate Config
      run: python3 tools/config_style_checker.py
    - name: Check for BOM
      uses: arma-actions/bom-check@master
    - name: .editorconfig Checker
      uses: jokoho48/action-editorconfig-checker@main
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Run Stringtable Checker
      run: cd tools/stringtableChecker && npm i &> /dev/null && cd ../../ && node tools/stringtableChecker/stringTableChecker.js
    - name: Check Functions
      run: node tools/prepchecker.js

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Lint (sqflint)
      uses: jokoho48/sqflint@master
      continue-on-error: true # No failure due to many false-positives
    - uses: actions/upload-artifact@master
      with:
       name: 'sqfLint Log'
       path: 'sqf.log'
    - name: Validate SQFLinter Logs
      run: python3 tools/sqf_linter_LogChecker.py

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT build
        run: hemtt release
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: '@LambsDanger'
          path: 'release/lambs-2*.zip'

  stringtables:
    runs-on: ubuntu-latest
    steps:
    - name: Install Python packages
      run: |
        pip3 install wheel
        pip3 install setuptools
        pip3 install pygithub
        pip3 install pygithub3
    - name: Checkout the source code
      uses: actions/checkout@master
    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py
    - name: Update Translation issue
      if: github.repository == 'nk3nny/LambsDanger' && github.ref	== 'refs/heads/master' && ! contains(github.event.head_commit.message, '[ci skip]')
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 tools/stringtableDeploy.py
